### ISSUE TITLE
VS 2022 build error

### ISSUE THREAD

**Issue by merco** [JonSaffron/Labyrinth#1]
![immagine](https://github.com/JonSaffron/Labyrinth/assets/1032335/8d7d3ae2-e27f-478d-b4b6-d2b77fdd4c47)

**Comment by JonSaffron** [comment]
Missing sprites added to repo. 
The problem with the fonts could be simply that you don't have Segoe UI Mono on your system (apparently it was probably installed on my system by XNA Game Studio). I have changed it over to Lucida Console instead which should be widely available.
